title: "Let there be light"
author: "Sarthak Jain"
description: "A piece of my mind" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "sarthakjain939@gmail.com"
twitter_username: "sarthakjain939"
github_username: "sarthak93"
linkedin_username: "sarthakjain93"
#facebook_username: username
#flickr_username: username
instagram_username: "sarthakjain93"
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: "https://sarthak93.github.io/blog"
      type: post
    values:
      tags: Other
